language: csharp
mono: none
dotnet: 2.0.0
branches:
  only:
  - master
script:
  - dotnet restore --source https://api.nuget.org/v3/index.json --source https://imedidata.myget.org/F/mdsol/auth/$MDSOL_NUGET_ACCESS_TOKEN/api/v3/index.json
  - dotnet build AspCoreApp.sln --configuration Release
  - sudo rm -r -f /InstallationPackage/
  - dotnet publish AspCoreApp/AspCoreApp.csproj --configuration Release --framework netcoreapp2.0 --no-restore --output ../InstallationPackage
after_success:
  - mkdir /UploadPackages/
  - tar cf /UploadPackages/mingestor.tar --use-compress-prog=pbzip2 /InstallationPackage
  - cp /UploadPackages/mingestor.tar /UploadPackages/mingestor_`%Y%m%d_%H%M%S`.tar
  - ls
  - ls /UploadPackages/
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET_NAME
  region: $AWS_S3_BUCKET_REGION
  skip_cleanup: true
  local_dir: /UploadPackages/
  cache_control: "max-age=21600"