language: csharp
mono: none
dotnet: 2.0.0
branches:
  only:
  - master
install:
  - sudo apt-get install mono-complete
  - wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
script:
  - mono nuget.exe sources Add -Name "MDSOL" -Source https://imedidata.myget.org/F/mdsol/auth/$MDSOL_NUGET_ACCESS_TOKEN/api/v3/index.json
  - dotnet restore
  - dotnet build ./AspCoreApp.sln --configuration Release
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET_NAME
  region: $AWS_S3_BUCKET_REGION
  skip_cleanup: true
  local_dir: ./AspCoreApp/bin/Release/netcoreapp2.0
  cache_control: "max-age=21600"